# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
description = "Signaling types the OpenTalk timer module"
documentation = "https://docs.rs/opentalk-types-signaling-timer"
edition = "2021"
homepage.workspace = true
license = "EUPL-1.2"
name = "opentalk-types-signaling-timer"
publish = true
repository.workspace = true
version.workspace = true

[features]
backend = []
frontend = []
